markdown: kramdown
collections:
  chapters:
    output: true
  macros:
    output: true
  instructions:
    output: true


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: default

      
      
      
      
      